"""
Planning strategies for AgentTool.

Strategies define HOW the agent decides what to do next:
- DirectStrategy: Single LLM call with tool_calling (simple, fast)
- ReactStrategy: Reason first, then act on immediate next step (thoughtful, adaptive)
- AdaptStrategy: Try simple first, decompose on failure (structural adaptation)
- ReflexionStrategy: Learn from mistakes through reflection (behavioral adaptation)
- AdaptiveReflexionStrategy: Combined ADaPT + Reflexion (multi-layered recovery)

The Strategy Pattern allows swapping planning approaches without changing AgentTool.

## Strategy contract (StrategyOutput)

Strategies are NOT responsible for detecting the `finish` meta tool — that's
AgentTool's job. The strategy only signals two things via `tool_calls`:

| `tool_calls` | Meaning |
|---|---|
| Empty (`[]`) | Strategy decided to terminate. AgentTool stops with `success`/`result` from StrategyOutput. (Typical case: LLM didn't emit any tool, including `finish`.) |
| Non-empty | AgentTool runs the tools. If `finish` is among them, AgentTool extracts its args and terminates. Otherwise the loop continues. |

Strategies set `success`/`result` ONLY when they return empty `tool_calls`
(strategy-internal terminate). For `finish`-driven termination, AgentTool
reads the args directly from the executed tool call.
"""

import typing as t
from abc import ABC, abstractmethod

from openai.types.chat import ChatCompletionMessageParam
from pydantic import BaseModel, ConfigDict, Field

from agents.agent_tool.plan_state import PlanState
from agents.llm_core.llm_client import ToolCall
from agents.tools_core.base_tool import BaseTool


class StrategyOutput(BaseModel):
    """
    Output from a planning strategy.

    Termination is signaled IMPLICITLY by `tool_calls`:
    - **Empty `tool_calls`**: strategy terminates the loop. AgentTool stops
      and returns with `success` and `result` from this StrategyOutput.
      Typical when the LLM emitted no tools at all.
    - **Non-empty `tool_calls`**: AgentTool runs the tools. If `finish` is
      among them, AgentTool extracts its args and terminates after execution.
      `success`/`result` on this StrategyOutput are then ignored — they're
      taken from `finish.arguments`.

    The strategy never special-cases `finish`. AgentTool owns that.
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    # Messages generated by the strategy (e.g., reasoning).
    # These get added to the conversation history.
    messages: list[ChatCompletionMessageParam] = Field(default_factory=list)

    # Tool calls to execute (if any). Empty list = terminate (use success/result below).
    tool_calls: list[ToolCall] = Field(default_factory=list)

    # Used ONLY when tool_calls is empty (strategy-internal terminate).
    # When tool_calls is non-empty, these fields are ignored — termination, if
    # any, comes from a `finish` tool call's arguments.
    success: bool = Field(default=True)
    result: str | None = Field(default=None)


class PlanningStrategy(ABC):
    """
    Base class for planning strategies.

    A strategy receives the current conversation state and decides:
    1. What messages to add (e.g., reasoning)
    2. What tools to call (if any)
    3. Whether the task is finished

    Each strategy owns its LLM client(s) and model configuration.
    """

    @abstractmethod
    async def plan(
        self,
        messages: list[ChatCompletionMessageParam],
        tools: list[BaseTool[t.Any, t.Any]],
        parallel_tool_calls: bool = True,
        plan_state: PlanState | None = None,
    ) -> StrategyOutput:
        """
        Generate next actions based on current conversation state.

        Args:
            messages: Current conversation history (read-only)
            tools: Available tools (including finish tool, and planstate_update
                if AgentTool has include_write_todos enabled)
            parallel_tool_calls: Allow LLM to return multiple tool calls
            plan_state: Durable plan state for this run, owned by AgentTool.
                Strategies may READ this to compose their prompts (e.g., re-inject
                the plan as data). Strategies MUST NOT mutate plan_state directly;
                mutation is reserved for the planstate_update tool (model-driven).
                The framework does NOT auto-mutate plan_state from tool results.
                Pass `None` if the strategy is plan-state-agnostic.

        Returns:
            StrategyOutput with the per-turn delta. Termination is implicit:
            empty tool_calls means terminate (AgentTool reads `success`/
            `result` from this StrategyOutput). Non-empty tool_calls means
            run the tools — if `finish` is among them, AgentTool will
            terminate after execution using `finish`'s args. Strategies
            never set or detect a `finished` flag explicitly.

            PlanState mutations happen via the model emitting a
            planstate_update tool call, not via this return value.
        """
        pass
